# Импорт, экспорт и типы данных

Задание из методички к Deductor Studio: импортировать CSV без заголовков, задать метки столбцам, выгрузить набор в текстовый файл, загрузить обратно и сменить тип `Поле2` на логический. Здесь то же самое сделано в pandas

In [1]:
#Импорт библиотек
import pandas as pd

In [2]:
#Импорт файла
df = pd.read_csv("data/input.csv", header=None)
df

    0  1    2   3   4           5   6
0   a  1  4.5   b   c  26/04/2011   d
1  a1  0  5.0  b1  c1         NaN  d1

In [3]:
#Задаем метки к столбцам: Поле1, Поле2, Поле3 и т.д.
df.columns = [f"Поле{i+1}" for i in range(len(df.columns))]
df

  Поле1  Поле2  Поле3 Поле4 Поле5       Поле6 Поле7
0     a      1    4.5     b     c  26/04/2011     d
1    a1      0    5.0    b1    c1         NaN    d1

In [4]:
#Экспортируем набор данных в текстовый файл Project1.txt
df.to_csv("data/Project1.txt", index=False, encoding="utf-8")

In [5]:
#Импортируем обратно Project1.txt
df2 = pd.read_csv("data/Project1.txt")
df2

  Поле1  Поле2  Поле3 Поле4 Поле5       Поле6 Поле7
0     a      1    4.5     b     c  26/04/2011     d
1    a1      0    5.0    b1    c1         NaN    d1

In [6]:
#Задаем метки к столбцам: Поле1, Поле2, Поле3 и т.д.
df2.columns = [f"Поле{i+1}" for i in range(len(df2.columns))]

In [7]:
#Меняем тип столбца 2 на булево значение
df2["Поле2"] = df2["Поле2"].astype(bool)
df2

  Поле1  Поле2  Поле3 Поле4 Поле5       Поле6 Поле7
0     a   True    4.5     b     c  26/04/2011     d
1    a1  False    5.0    b1    c1         NaN    d1

In [8]:
#Сохраняем
df2.to_csv("data/Project1_final.csv", index=False, encoding="utf-8")