# Фильтрация и очистка

Первая часть продолжает предыдущий ноутбук: статистика, пропуски, форматирование и фильтр по пустым значениям. Вторая часть работает с `CreditSample.txt` (заявки на кредит): сортировка, замена значений в категориальных полях и комбинированный фильтр вида «условие a ИЛИ условие b»

Файл данных синтетический, той же структуры, что и в поставке Deductor (см. `../generate_data.py`)

In [1]:
#Импорт библиотек
import pandas as pd

In [2]:
#Импорт файла
df = pd.read_csv("data/Project1_final.csv")
df

  Поле1  Поле2  Поле3 Поле4 Поле5       Поле6 Поле7
0     a   True    4.5     b     c  26/04/2011     d
1    a1  False    5.0    b1    c1         NaN    d1

In [3]:
#Просмотр статистики
df.describe(include="all")

       Поле1 Поле2     Поле3 Поле4 Поле5       Поле6 Поле7
count      2     2  2.000000     2     2           1     2
unique     2     2       NaN     2     2           1     2
top        a  True       NaN     b     c  26/04/2011     d
freq       1     1       NaN     1     1           1     1
mean     NaN   NaN  4.750000   NaN   NaN         NaN   NaN
std      NaN   NaN  0.353553   NaN   NaN         NaN   NaN
min      NaN   NaN  4.500000   NaN   NaN         NaN   NaN
25%      NaN   NaN  4.625000   NaN   NaN         NaN   NaN
50%      NaN   NaN  4.750000   NaN   NaN         NaN   NaN
75%      NaN   NaN  4.875000   NaN   NaN         NaN   NaN
max      NaN   NaN  5.000000   NaN   NaN         NaN   NaN

In [4]:
#Пропуски
df.isnull().sum()

Поле1    0
Поле2    0
Поле3    0
Поле4    0
Поле5    0
Поле6    1
Поле7    0
dtype: int64

In [5]:
#Форматирование Поле3, добавляем 'кг.'
df_K1 = df.copy()
df_K1["Поле3"] = df_K1["Поле3"].astype(str) + " кг."
df_K1

  Поле1  Поле2    Поле3 Поле4 Поле5       Поле6 Поле7
0     a   True  4.5 кг.     b     c  26/04/2011     d
1    a1  False  5.0 кг.    b1    c1         NaN    d1

In [6]:
#Оставляем столбцы начиная с 4го
df_K2 = df_K1.copy()
df_K2 = df_K2.iloc[:, 3:]
df_K2

  Поле4 Поле5       Поле6 Поле7
0     b     c  26/04/2011     d
1    b1    c1         NaN    d1

In [7]:
#Фильтруем df_K1 по пустым значениям в Поле6
df_filtered = df_K1[df_K1["Поле6"].notna()]
df_filtered

  Поле1  Поле2    Поле3 Поле4 Поле5       Поле6 Поле7
0     a   True  4.5 кг.     b     c  26/04/2011     d

In [8]:
#Возвращаемся к датафрейму без фильтра
df_K1

  Поле1  Поле2    Поле3 Поле4 Поле5       Поле6 Поле7
0     a   True  4.5 кг.     b     c  26/04/2011     d
1    a1  False  5.0 кг.    b1    c1         NaN    d1

In [9]:
#Импорт CreditSample.txt
df = pd.read_csv("data/CreditSample.txt", sep="\t", encoding="cp1251")
df.head(3)

,Код,"Размер ссуды, руб","Срок ссуды, мес",Цель ссуды,"Среднемесячный доход, руб","Среднемесячный расход, руб",Основное направление расходов,Количество лет,Семейное положение,Количество иждивенцев,Наличие недвижимости,Давать кредит
0,1,8000,18,Покупка и ремонт недвижимости,6000,3000,Затраты на образование (в т.ч. детей),38,Да,3,Нет,ИСТИНА
1,2,7500,24,Иное,14000,12000,Покупка товаров длит. пользования,61,Да,0,Нет,ЛОЖЬ
2,3,17000,12,Покупка автомобиля,3500,1500,"Содержание/аренда недвижимости, а/т",45,Нет,1,Да,ЛОЖЬ

In [10]:
#Сортировка
df = df.sort_values(by=["Срок ссуды, мес", "Размер ссуды, руб", "Количество иждивенцев"])
df.head(3)

,Код,"Размер ссуды, руб","Срок ссуды, мес",Цель ссуды,"Среднемесячный доход, руб","Среднемесячный расход, руб",Основное направление расходов,Количество лет,Семейное положение,Количество иждивенцев,Наличие недвижимости,Давать кредит
147,148,2500,6,Покупка и ремонт недвижимости,9000,7500,Покупка товаров длит. пользования,33,Нет,0,Нет,ЛОЖЬ
61,62,5500,6,Покупка товара,10000,7000,Затраты на образование (в т.ч. детей),58,Да,0,Нет,ЛОЖЬ
93,94,5500,6,Покупка и ремонт недвижимости,8000,6000,"Содержание/аренда недвижимости, а/т",43,Нет,1,Да,ЛОЖЬ

In [11]:
#Замена в поле Семейное положение
df["Семейное положение"] = df["Семейное положение"].replace({
    "Да": "Женат/замужем",
    "Нет": "Холост/Не замужем"
})
df["Семейное положение"]

147    Холост/Не замужем
61         Женат/замужем
93     Холост/Не замужем
159    Холост/Не замужем
42     Холост/Не замужем
             ...
76         Женат/замужем
149    Холост/Не замужем
98         Женат/замужем
109    Холост/Не замужем
117    Холост/Не замужем
Name: Семейное положение, Length: 200, dtype: str

In [12]:
#Замена в поле Количество иждивенцев
df["Количество иждивенцев_REPLACE"] = df["Количество иждивенцев"].replace({
    0: "Нет",
    1: "1",
    2: "2 и более",
    3: "2 и более"
})
df["Количество иждивенцев_REPLACE"]

147          Нет
61           Нет
93             1
159    2 и более
42             1
         ...
76             1
149          Нет
98           Нет
109          Нет
117          Нет
Name: Количество иждивенцев_REPLACE, Length: 200, dtype: object

In [13]:
#Удаляем старое поле и переименовываем новое
df = df.drop(columns=["Количество иждивенцев"])
df = df.rename(columns={"Количество иждивенцев_REPLACE": "Иждивенцы"})
df["Иждивенцы"]

147          Нет
61           Нет
93             1
159    2 и более
42             1
         ...
76             1
149          Нет
98           Нет
109          Нет
117          Нет
Name: Иждивенцы, Length: 200, dtype: object

In [14]:
#Фильтр Иждивенцы != Нет
df6 = df[df["Иждивенцы"] != "Нет"]
print("Фильтр (Иждивенцы != Нет):", len(df6))

Фильтр (Иждивенцы != Нет): 133

In [15]:
#Фильтр Иждивенцы != н/д (в синтетических данных пропусков нет, фильтр ничего не отсекает)
df7 = df[df["Иждивенцы"] != "н/д"]
print("Фильтр (Иждивенцы != н/д):", len(df7))

Фильтр (Иждивенцы != н/д): 200

In [16]:
#Фильтр по условиям (a или b)
df8 = df6[((df6["Размер ссуды, руб"].between(2000, 5000)) & (df6["Цель ссуды"] == "Покупка товара")) |
          (df6["Цель ссуды"] == "Иное")]
print("Фильтр (a или b):", len(df8))

Фильтр (a или b): 24

In [17]:
#Сортировка по полю Код
df9 = df8.sort_values(by="Код")
df9.head(5)

,Код,"Размер ссуды, руб","Срок ссуды, мес",Цель ссуды,"Среднемесячный доход, руб","Среднемесячный расход, руб",Основное направление расходов,Количество лет,Семейное положение,Наличие недвижимости,Давать кредит,Иждивенцы
4,5,16500,6,Иное,7500,4000,"Содержание/аренда недвижимости, а/т",55,Холост/Не замужем,Нет,ИСТИНА,2 и более
5,6,7500,24,Иное,7500,5000,"Содержание/аренда недвижимости, а/т",30,Женат/замужем,Нет,ЛОЖЬ,1
20,21,13500,24,Иное,10000,3000,Затраты на образование (в т.ч. детей),31,Женат/замужем,Нет,ЛОЖЬ,2 и более
28,29,12500,18,Иное,14000,5500,Затраты на образование (в т.ч. детей),52,Холост/Не замужем,Нет,ИСТИНА,1
32,33,15000,18,Иное,3000,1500,Выплаты по кредитам/займам,67,Холост/Не замужем,Да,ИСТИНА,2 и более

In [18]:
#Сохранение
df9.to_csv("data/Project2_final.csv", index=False, encoding="utf-8")