# Скользящее окно

Превращаем временной ряд в таблицу для обучения: глубина погружения 2 (два прошлых значения), горизонт прогноза 1. Сначала для одного ряда, потом для многомерного. Данные взяты из таблиц 3.3 и 3.6 методички и заданы прямо в коде

In [1]:
import pandas as pd

df = pd.DataFrame({
    "date": [
        "01.01.2023",
        "01.02.2023",
        "01.03.2023",
        "01.04.2023",
        "01.05.2023",
        "01.06.2023"
    ],
    "clients": [1540, 960, 1150, 1230, 1056, 995]
})

depth = 2    # x(n-2), x(n-1)
horizon = 1  # x(n+1)

df_sw = df.copy()
df_sw["x(n-2)"] = df_sw["clients"].shift(2)
df_sw["x(n-1)"] = df_sw["clients"].shift(1)
df_sw["x(n)"]   = df_sw["clients"]
df_sw["x(n+1)"] = df_sw["clients"].shift(-1)

df_sw

         date  clients  x(n-2)  x(n-1)  x(n)  x(n+1)
0  01.01.2023     1540     NaN     NaN  1540   960.0
1  01.02.2023      960     NaN  1540.0   960  1150.0
2  01.03.2023     1150  1540.0   960.0  1150  1230.0
3  01.04.2023     1230   960.0  1150.0  1230  1056.0
4  01.05.2023     1056  1150.0  1230.0  1056   995.0
5  01.06.2023      995  1230.0  1056.0   995     NaN

In [2]:
df_sw_clean = df_sw.dropna().reset_index(drop=True)
df_sw_clean

         date  clients  x(n-2)  x(n-1)  x(n)  x(n+1)
0  01.03.2023     1150  1540.0   960.0  1150  1230.0
1  01.04.2023     1230   960.0  1150.0  1230  1056.0
2  01.05.2023     1056  1150.0  1230.0  1056   995.0

In [3]:
df2 = pd.DataFrame({
    "i": [1, 2, 3, 4, 5, 6],
    "a": [8, 5, 4, 10, 12, 9],
    "b": [111, 112, 106, 114, 96, 116]
})

depth = 2

df_multi = df2.copy()

# создаём лаги
df_multi["a(n-1)"] = df_multi["a"].shift(1)
df_multi["a(n-2)"] = df_multi["a"].shift(2)
df_multi["b(n-1)"] = df_multi["b"].shift(1)
df_multi["b(n-2)"] = df_multi["b"].shift(2)

# удаляем неполные строки
df_multi_clean = df_multi.dropna().reset_index(drop=True)

df_multi_clean

   i   a    b  a(n-1)  a(n-2)  b(n-1)  b(n-2)
0  3   4  106     5.0     8.0   112.0   111.0
1  4  10  114     4.0     5.0   106.0   112.0
2  5  12   96    10.0     4.0   114.0   106.0
3  6   9  116    12.0    10.0    96.0   114.0